# /home/artbdr/Documents/repos/spotify-wrapped/dash/.streamlit/secrets.toml

[pg]
host = "spotify-rds.cp4i4ikiq46s.us-east-2.rds.amazonaws.com"
port = 5432
dbname = "postgres"
user = "admin_postgres"
password = "Ar+sinistr0"
sslmode = "require"

